# -----------------------------
# AVIA 数据集配置
# -----------------------------
common:
  # 传感器话题
  img_topic: "/alphasense/cam0/image_raw"
  lid_topic: "/livox/lidar"
  imu_topic: "/os_cloud_node/imu"
  # 1: 启用, 0: 关闭
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

# LiDAR-IMU / Camera-LiDAR 外参
extrin_calib:
  extrinsic_T: [0.04165, 0.02326, -0.0284]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [0.00610193,-0.999863,-0.0154172,
        -0.00615449,0.0153796,-0.999863,
        0.999962,0.00619598,-0.0060598] 
  Pcl: [0.0194384, 0.104689,-0.0251952]

time_offset: 
  # 时间偏移补偿
  imu_time_offset: 0.0
  img_time_offset: 0.1
  exposure_time_init: 0.0

# 点云预处理
preprocess:
  point_filter_num: 1
  filter_size_surf: 0.1
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 6
  blind: 0.8

# 视觉里程计参数
vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

# IMU 参数
imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

# 激光里程计参数
lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

# 局部地图参数
local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

# 发布控制
publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

# 轨迹输出
evo:
  seq_name: "eee_03"
  pose_output_en: true

# PCD 保存配置
pcd_save:
  pcd_save_en: true
  type: 0 # 0: World Frame, 1: Body Frame;
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # 每个 pcd 文件累积多少 LiDAR 帧
  # -1: 全部帧写入同一个文件（超长序列可能占用较大内存）

# 图像保存配置
image_save:
  img_save_en: true
  interval: 1
